### PR TITLE
Skip unresolvable dependencies

### LINKED ISSUE #117: [BUG] nexusIQScan and nexusIQIndex fail to resolve dependencies with composite builds or dependency substitution
**Describe the bug**
nexusIQScan and nexusIQIndex tasks can fail to resolve dependencies if project is using a gradle composite build or using dependency substitution rules

**To Reproduce**
1. [Download sample project](https://github.com/ibevilinc/SonatypeScanGradlePluginIssueSample)
2. Running `./gradew nexusIQIndex` inside of `app` works, however it fails when executed inside of either `appIncludedBuild` or `appModuleSubstitution` where the sample library is built as source fails the a dependency resolution error during the sonatypeCopyConfiguration task

**Expected behavior**

nexusIQScan & nexusIQIndex should work regardless of project configuration rules.

**Screenshots**
Screen Shot 2022-08-05 at 1 24 28 PM

**Desktop (please complete the following information):**
 - OS: OSX 12.5 & Ubuntu 22.04
 - Gradle Version: 7.5
 - JVM Version and Flavor: Temurin-11.0.16+8
 - Nexus IQ Server Version: n/a
 - Version 2.4.0

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by guillermo-varela**
When using dependency substitution to replace an external dependency with a local project, as explained in #117, the plugin is unable to resolve such dependency.

When it gets here:
https://github.com/sonatype-nexus-community/scan-gradle-plugin/blob/6de7fa931531dc11a3ea64c9b575604c50e6f008/src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java#L178-L184

We get the dependency as an external one instead of an instance of `ProjectDependency` and there doesn't seem to be a way to differenciate that dependency from others.

With this PR the plugin will try once to resolve the failed configuration as usual and if that fails a second attempt will be made but this time skipping and logging the dependencies that cannot be resolved.

```
> Task :nexusIQScan
Unable to process the dependency com.example.libs:samplelib:1.0.0 in project app and configuration releaseCompileClasspath
Unable to process the dependency com.example.libs:samplelib:1.0.0 in project app and configuration releaseRuntimeClasspath
```

Dependencies from the replacing external module would have to be evaluated separately by running the plugin there.

It relates to the following issue #s:
* Fixes #117

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

### CODE REVIEW

File: src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java [hunk 1]
```diff
@@ -172,20 +175,48 @@ <T> Stream<T> getDependencies(
...
+        copyConfiguration.getDependencies().add(dependency);
+
+        if (skipUnresolvableDependencies) {
+          try {
+            originalConfiguration.files(dependency);
+          }
+          catch (Exception e) {
+            log.warn("Unable to process the dependency " + dependency.getGroup() + ":" + dependency.getName() + ":"
+                + dependency.getVersion() + " in project " + project.getName() + " and configuration "
+                + originalConfiguration.getName());
```
Comment (shaikhu) [inline src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java:212]: Suggestion. Maybe better to use placeholders rather then string concatenate e.g.
```            log.warn("Unable to process the dependency {}:{}:{} in project {} and configuration {}",
                dependency.getGroup(), dependency.getName(), dependency.getVersion(), dependency.getName(), originalConfiguration.getName());
```

File: src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java [hunk 2]
```diff
@@ -172,20 +175,48 @@ <T> Stream<T> getDependencies(
...
-          project.evaluationDependsOn(dependencyProject.getPath());
-        }
-        else {
-          copyConfiguration.getDependencies().add(dependency);
+      try {
+        return function.apply(copyConfiguration.getResolvedConfiguration());
+      }
+      catch (Exception lastResortException) {
+        copyConfiguration = copyDependencies(project, originalConfiguration, true);
+        return function.apply(copyConfiguration.getResolvedConfiguration());
```
Comment (shaikhu) [inline src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java:185]: I'm just wondering how this third check  will effect performance (if at all) ? :thinking: Other builds should resolve as normal right? Seems this scenario is very specific e.g. an android build using dependency substitution rules.  I suppose these builds might take a little longer but at least they complete (and skipped dependencies are logged)

File: src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java [hunk 3]
```diff
@@ -172,20 +175,48 @@ <T> Stream<T> getDependencies(
...
-        if (dependency instanceof ProjectDependency) {
-          Project dependencyProject = ((ProjectDependency) dependency).getDependencyProject();
-          project.evaluationDependsOn(dependencyProject.getPath());
-        }
-        else {
-          copyConfiguration.getDependencies().add(dependency);
+      try {
+        return function.apply(copyConfiguration.getResolvedConfiguration());
+      }
+      catch (Exception lastResortException) {
```
Comment (shaikhu) [inline src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java:183]: Question. Instead of catching large scoped `Exception` is it worth catching the more specific `ResolveException` ?

File: src/test/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinderTest.java [hunk 4]
```diff
@@ -410,6 +410,30 @@ public void testGetDependencies_ResolvedArtifacts_WithError() {
     assertThat(list.get(0).getId().getComponentIdentifier().toString()).isEqualTo(COMMONS_COLLECTIONS_DEPENDENCY);
   }
 
+  @Test
+  public void testGetDependencies_ResolvedArtifacts_WithDoubleError() {
```
Comment (shaikhu) [inline src/test/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinderTest.java:414]: Suggestion. Maybe we can rename this to be clearer what is being tested? e.g. testGetDependencies_ResolvedArtifacts_Skip_Unresolvable_Dependencies()

**Review by shaikhu — APPROVED** [review]
+1 with few minor comments/suggestions

File: src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java (hunk 2 above)
Comment (guillermo-varela) [reply src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java:185]: > I'm just wondering how this third check will effect performance? 🤔 Other builds should resolve as normal right? Seems this scenario is very specific e.g. an android build using dependency substitution rules. I suppose these builds might take a little longer but at least they complete (and skipped dependencies are logged)

Right, this is only happening for Android projects and would only be executed if the first attempt fails.
At the end, any extra delay would be preferred to a failure at this point.

File: src/test/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinderTest.java (hunk 4 above)
Comment (guillermo-varela) [reply src/test/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinderTest.java]: > Suggestion. Maybe we can rename this to be clearer what is being tested? e.g. `testGetDependencies_ResolvedArtifacts_Skip_Unresolvable_Dependencies()`

Done: 67073e7b27d33ade3f14e05627408a38e954715d

File: src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java (hunk 3 above)
Comment (guillermo-varela) [reply src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java]: > Question. Instead of catching large scoped `Exception` is it worth catching the more specific `ResolveException` ?

Done: 67073e7b27d33ade3f14e05627408a38e954715d

File: src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java (hunk 1 above)
Comment (guillermo-varela) [reply src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java]: > Suggestion. Maybe better to use placeholders rather then string concatenate e.g. `log.warn("Unable to process the dependency {}:{}:{} in project {} and configuration {}", dependency.getGroup(), dependency.getName(), dependency.getVersion(), dependency.getName(), originalConfiguration.getName()); `

Done: 67073e7b27d33ade3f14e05627408a38e954715d
