### PR TITLE
#82 Creates an application with a given organization ID if not exists

### LINKED ISSUE #82: [FEATURE] Specify NexusIQ Organization for Application
* **What are you trying to do?**
Currently, depending on NexusIQ configuration, new applications are placed in the Default organization.  This creates a maintenance burden for administrators who must later move the application to the appropriate organization.  The current behavior also produces reports based on the policies of the Default organization which may not be appropriate for the application being scanned.  I'd like to specify in the extension DSL the organization the application should be created under when it does not already exist.  If the application already exists under a different organization, then the scan should continue but provide a warning.  The application should not be moved.  If the specified organization does not exist, the build should fail with an appropriate message.
 
* **What feature or behavior is this required for?**
Moves the initial assignment of application organization to the developer instead of an administrator.

* **How could we solve this issue? (Not knowing is okay!)**
Use the NexusIQ REST API to lookup the specified organization and use it to create the new application.

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

### PR DESCRIPTION
**Pull request by guillermo-varela**
Nexus IQ Server provides a feature where a non-existing application can be created automatically under a predefined organization: https://help.sonatype.com/iqserver/managing/application-management/managing-automatic-applications

Issue #82 exposed a use case where not all applications to be created automatically should be under the same organization.

This pull-requests adds this feature by using the public APIs from Nexus IQ Server to validate if an application exists under a given organization and creates it if none is found.

It relates to the following issue #s:
* Fixes #82 

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

### CODE REVIEW

File: src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqScanTask.java [hunk 1]
```diff
@@ -131,6 +129,31 @@ public void scan() {
     }
   }
 
+  private void verifyOrCreateApplication(InternalIqClient iqClient) throws IqClientException {
+    if (StringUtils.isNoneBlank(extension.getOrganizationId(), extension.getApplicationId())) {
+      NexusIqApi nexusIqApi = NexusIqApi.build(extension.getServerUrl(), extension.getUsername(),
+          extension.getPassword(), buildUserAgent());
+
+      boolean applicationExists = nexusIqApi
```
Comment (shaikhu) [inline src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqScanTask.java:137]: Question. Before checking if the application exists, is it worth checking the organisation id is valid and actually refers to an existing organisation, and throw an exception if it doesn't? Otherwise is it possible to create an application for an org which doesn't exist?

Comment (guillermo-varela) [reply src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqScanTask.java:137]: > Question. Before checking if the application exists, is it worth checking the organisation id is valid and actually refers to an existing organisation, and throw an exception if it doesn't? Otherwise is it possible to create an application for an org which doesn't exist?

When seting an unexisting organization ID the operation fails and the user gets this output in console/terminal (using `667371c75ffd4662a9b6d4ee1f5f0d3d111` as example of an invalid org id):
```
Could not scan the project: [404 Not Found] during [GET] to [http://localhost:8070/api/v2/applications/organization/667371c75ffd4662a9b6d4ee1f5f0d3d111] [NexusIqApi#getApplicationsByOrganizationId(String)]: [Cannot find organization with ID 667371c75ffd4662a9b6d4ee1f5f0d3d111.]
```

**Review by shaikhu — APPROVED** [review]
LGTM
