### PR TITLE
Fix commit hash discovery

### LINKED ISSUE #92: [FEATURE] Discover git commit hash
When running the plugin for Nexus IQ we get this in the output: `Could not discover git commit hash via automation`

It would be nice to see if we can get the git commit hash.

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

### PR DESCRIPTION
**Pull request by eduard-tita**
This pull request makes the following changes:
* Provide a better default value for the `scanFolderPath` field in `NexusIqPluginScanExtension` (the current value will never work).
* Document how to set the `scanFolderPath` field in order to properly collect the commit hash during scans.

It relates to the following issue #s:
* Fixes #92 

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

### CODE REVIEW

**Comment by shaikhu** [comment]
Tested locally with sample gradle project and was able to discover commit hash :tada: 
image

**Review by shaikhu — APPROVED** [review]
LGTM

File: src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqPluginScanExtension.java [hunk 1]
```diff
@@ -61,7 +61,7 @@ public NexusIqPluginScanExtension(Project project) {
     organizationId = "";
     simulationEnabled = false;
     simulatedPolicyActionId = PolicyAction.NONE.toString();
-    scanFolderPath = project.getBuildDir() + File.separator + SONATYPE_CLM_FOLDER + File.separator;
+    scanFolderPath = System.getProperty("user.dir");
```
Comment (guillermo-varela) [inline src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqPluginScanExtension.java:64]: > Path to the project root

If that's the correct meaning, then this is the appropiated default value:

```suggestion
    scanFolderPath = project.getRootDir().getAbsolutePath();
```

File: README.md [hunk 2]
```diff
@@ -175,6 +176,7 @@ nexusIQScan {
     modulesExcluded = listOf("module-1", "module-2") // Optional. For multi-module projects, the names of the sub-modules to exclude from scanning and evaluation.
     dirExcludes = "some-ant-pattern" // Optional. Comma separated ant-like glob patterns to select directories/archives that should be excluded. For Android projects we suggest using "**/classes.jar,**/annotations.zip,**/lint.jar,**/internal_impl-*.jar"
     dirIncludes = "some-ant-pattern" // Optional. Comma separated ant-like glob patterns to select directories/archives that should be examined
+    scanFolderPath = "/path/to/project/root" // Optional. Path to the project root, under which the '.git' folder usually resides. Defaults to the working directory (where gradle is executed).
```
Comment (guillermo-varela) [inline README.md:179]:
```suggestion
    scanFolderPath = "/path/to/project/root" // Optional. Path to the project root, under which the '.git' folder usually resides. Defaults to the project's root directory.
```

File: README.md [hunk 3]
```diff
@@ -158,6 +158,7 @@ nexusIQScan {
     modulesExcluded = ['module-1', 'module-2'] // Optional. For multi-module projects, the names of the sub-modules to exclude from scanning and evaluation.
     dirExcludes = 'some-ant-pattern' // Optional. Comma separated ant-like glob patterns to select directories/archives that should be excluded. For Android projects we suggest using '**/classes.jar,**/annotations.zip,**/lint.jar,**/internal_impl-*.jar'
     dirIncludes = 'some-ant-pattern' // Optional. Comma separated ant-like glob patterns to select directories/archives that should be examined
+    scanFolderPath = '/path/to/project/root' // Optional. Path to the project root, under which the '.git' folder usually resides. Defaults to the working directory (where gradle is executed).
```
Comment (guillermo-varela) [inline README.md:161]:
```suggestion
    scanFolderPath = '/path/to/project/root' // Optional. Path to the project root, under which the '.git' folder usually resides. Defaults to the project's root directory.
```

File: src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqPluginScanExtension.java [hunk 4]
```diff
@@ -61,7 +61,7 @@ public NexusIqPluginScanExtension(Project project) {
     organizationId = "";
     simulationEnabled = false;
     simulatedPolicyActionId = PolicyAction.NONE.toString();
-    scanFolderPath = project.getBuildDir() + File.separator + SONATYPE_CLM_FOLDER + File.separator;
```
Comment (guillermo-varela) [inline src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqPluginScanExtension.java:64]: `import java.io.File;` becomes unused after this. It's better to remove that import

File: src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqPluginScanExtension.java (hunk 1 above)
Comment (eduard-tita) [reply src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqPluginScanExtension.java:64]: That would be ideal, but I could not find a way to detect the path to the project root.

`project.getRootDir()` is not what the developers understand as the project root i.e. the folder where the project is checked out from SCM. `project.getRootDir()` is a temporary folder where `gradle` does the build. This is not what we want. It will never contain the `.git` folder, which is needed for the commit hash discovery (the original value relied on `project.getBuildDir()`, which sometimes coincides with `project.getRootDir()` and is also a temporary folder). 

The default value I suggest above is gradle's working directory. In most cases developers run gradle commands in the root directory of the project. If that's the case, that folder contains the `.git` folder.

File: README.md (hunk 2 above)
Comment (eduard-tita) [reply README.md:179]: This does not reflect my suggestion (see comment above).

File: README.md (hunk 3 above)
Comment (eduard-tita) [reply README.md:161]: Same as above

File: src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqPluginScanExtension.java (hunk 4 above)
Comment (eduard-tita) [reply src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqPluginScanExtension.java:64]: Thanks. Removed in [fde1eac](https://github.com/sonatype-nexus-community/scan-gradle-plugin/pull/107/commits/fde1eac60cff962fe3eccb07150860370a1d8179)

File: src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqPluginScanExtension.java (hunk 1 above)
Comment (guillermo-varela) [reply src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqPluginScanExtension.java:63]: > That would be ideal, but I could not find a way to detect the path to the project root.

From the [Gradle javadoc](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#getRootDir--):
> Returns the root directory of this project. The root directory is the project directory of the root project.

It seems `project.getRootDir()` is exactly what is needed and also it's not a temporary folder.

Comment (eduard-tita) [reply src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/scan/NexusIqPluginScanExtension.java]: You are right, @guillermo-varela. I was confused by checking the value of `project.getRootDir()` while debugging a test, which obviously runs in a temp folder.

File: README.md (hunk 2 above)
Comment (eduard-tita) [reply README.md]: I don't think we need to document it at all. The project's root directory is what we need. Users can only mess it up.

Comment (guillermo-varela) [reply README.md]: Agreed!

**Review by guillermo-varela — APPROVED** [review]
+1

**Comment by guillermo-varela** [comment]
Thanks for your contribution @eduard-tita 👍
